//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.19 at 05:42:06 PM CET 
//


package com.scit.xml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="journal_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="submitted"/>
 *               &lt;enumeration value="cancelled"/>
 *               &lt;enumeration value="rejected"/>
 *               &lt;enumeration value="accepted"/>
 *               &lt;enumeration value="revision"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="submission_dates" type="{http://www.scit.org/schema/paper}dates"/>
 *         &lt;element name="revision_dates" type="{http://www.scit.org/schema/paper}dates"/>
 *         &lt;element name="acceptance_dates" type="{http://www.scit.org/schema/paper}dates" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "journalId",
    "category",
    "status",
    "submissionDates",
    "revisionDates",
    "acceptanceDates"
})
@XmlRootElement(name = "paper_info", namespace = "http://www.scit.org/schema/paper")
public class PaperInfo {

    @XmlElement(name = "journal_id", namespace = "http://www.scit.org/schema/paper")
    protected String journalId;
    @XmlElement(namespace = "http://www.scit.org/schema/paper")
    protected String category;
    @XmlElement(namespace = "http://www.scit.org/schema/paper", required = true)
    protected String status;
    @XmlList
    @XmlElement(name = "submission_dates", namespace = "http://www.scit.org/schema/paper", required = true, nillable = true)
    protected List<XMLGregorianCalendar> submissionDates;
    @XmlList
    @XmlElement(name = "revision_dates", namespace = "http://www.scit.org/schema/paper", required = true, nillable = true)
    protected List<XMLGregorianCalendar> revisionDates;
    @XmlList
    @XmlElement(name = "acceptance_dates", namespace = "http://www.scit.org/schema/paper", required = true, nillable = true)
    protected List<XMLGregorianCalendar> acceptanceDates;

    /**
     * Gets the value of the journalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournalId() {
        return journalId;
    }

    /**
     * Sets the value of the journalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournalId(String value) {
        this.journalId = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the submissionDates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the submissionDates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubmissionDates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getSubmissionDates() {
        if (submissionDates == null) {
            submissionDates = new ArrayList<XMLGregorianCalendar>();
        }
        return this.submissionDates;
    }

    /**
     * Gets the value of the revisionDates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the revisionDates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRevisionDates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getRevisionDates() {
        if (revisionDates == null) {
            revisionDates = new ArrayList<XMLGregorianCalendar>();
        }
        return this.revisionDates;
    }

    /**
     * Gets the value of the acceptanceDates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acceptanceDates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcceptanceDates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getAcceptanceDates() {
        if (acceptanceDates == null) {
            acceptanceDates = new ArrayList<XMLGregorianCalendar>();
        }
        return this.acceptanceDates;
    }

}
